### ISSUE TITLE
Saving and loading user configurations 

### ISSUE THREAD

**Issue by hikasuun** [hikasuun/WeatherNode#23]
Implement method for saving username, email, location vector list, and notification vector list into a local file, like a JSON file.

**Comment by hikasuun** [comment]
How far are you on this, I checked it and the XML file shows that there is nothing saved upon exit?

**Comment by sleep-walkerr** [comment]
Did you look at the userstate xml or the savestate xml? I decided to not use the userstate xml file so ofc it's going to be empty

**Comment by hikasuun** [comment]
Closed with #65
